<?php
// This is an example configuration file.
// The actual config.php file will be generated by the installer.

// Database Configuration
define('DB_HOST', 'your_db_host');
define('DB_USER', 'your_db_user');
define('DB_PASS', 'your_db_password');
define('DB_NAME', 'your_db_name');

// Site Configuration
define('SITE_URL', 'http://your_site_url');

// Define App Root
define('APPROOT', dirname(__DIR__));

// Start session
if(!session_id()) session_start();
?>